export const PROJECT_DETAIL = {
  'Slope Ninja': {
    title: 'Slope Ninja',
    description: 'Snow updates for Tahoe Resorts',
    subDescription: 'Web and Mobile',
    shortSkills: ['React', 'React Native', 'DynamoDB', 'node.js', '...', 'UI/UX'],
    longSkills: ['React', 'React Native', 'DynamoDB', 'node.js', 'Docker', 'PostgreSQL', 'Knex', 'Koa', 'Bootstrap Grid', 'Redux', 'Sketch', 'UI/UX'],
  },
  NDAify: {
    title: 'NDAify',
    description: 'NDA-walls for your business secrets',
    subDescription: 'Web',
    shortSkills: ['React', 'i18n', 'Stripe API', 'OAuth', 'Docker', '...', 'Next.js'],
    longSkills: ['React', 'i18n', 'Stripe API', 'OAuth', 'Docker', 'node.js', 'Koa', 'DynamoDB', 'AWS SQS', 'AWS S3', 'AWS Lambda', 'AWS SES', 'Open API', 'JWT', 'Markdown', 'Animations', 'Figma', 'UI/UX', 'Next.js'],
  },
  wfcache: {
    title: 'wfcache',
    description: 'Multi-layered cache with waterfall hit propagation and built-in storage adapters for DynamoDB, Redis, BigCache (in-memory)',
    shortSkills: ['Go', 'DynamoDB', 'Redis'],
    longSkills: ['Go', 'DynamoDB', 'Redis'],
  },
  'Building Block': {
    title: 'Blocks',
    description: 'Building blocks are basic units of code from which larger modules can be built',
    shortSkills: ['JavaScript', 'TypeScript', 'Babel', 'Lerna', 'CircleCI'],
    longSkills: ['JavaScript', 'TypeScript', 'Babel', 'Lerna', 'CircleCI'],
  },
  Trulia: {
    title: 'Trulia',
    description: 'Real estate listings and rental properties',
    subDescription: 'Web',
    shortSkills: ['React', 'GraphQL', 'Apollo', 'Docker', '...', 'TypeScript'],
    longSkills: ['React', 'GraphQL', 'Apollo', 'Docker', 'Next.js', 'Go', 'Gin', 'MySQL', 'PHP', 'Redux', 'Selenium', 'Cypress', 'Jenkins', 'Groovy', 'TypeScript', 'DynamoDB'],
    link: 'https://trulia.com',
    text: 'trulia.com',
    enableCards: true,
  },
  Netflix: {
    title: 'Netflix',
    description: 'Watch TV Shows Online, Watch Movies Online',
    subDescription: 'Web',
    shortSkills: ['React', 'GraphQL', '...', 'TypeScript'],
    longSkills: ['React', 'GraphQL', 'TypeScript'],
    link: 'https://www.netflix.com/tudum',
    text: 'netflix.com',
    enableCards: true,
  },
  Astroworker: {
    title: 'Astroworker',
    description: 'Get on-demand work',
    subDescription: 'Web',
    shortSkills: ['React', 'Redux', 'node.js', '...', 'UI/UX'],
    longSkills: ['React', 'Redux', 'node.js', 'PostgreSQL', 'JWT', 'AWS S3', 'AWS SES', 'Koa', 'Knex', 'UI/UX'],
    link: 'http://astroworker.com',
    text: 'astroworker.com',
  },
  Debut: {
    title: 'Debut',
    description: 'Beautiful, simple, clutter-free newsletters',
    subDescription: 'Web and Mobile',
    shortSkills: ['React', 'React Native', 'Redux', '...', 'UI/UX'],
    longSkills: ['React', 'React Native', 'Redux', 'Bootstrap Grid', 'UI/UX'],
  },
  Bagpal: {
    title: 'Bagpal',
    description: 'Social Platform for exchanging handbags',
    subDescription: 'Mobile',
    shortSkills: ['UI/UX'],
    longSkills: ['UI/UX'],
  },
  'Once Upon a Cloud': {
    title: 'Once Upon a Cloud',
    description: 'VR experience to learn about the earth water cycle',
    subDescription: 'Virtual Reality on Oculus',
    shortSkills: ['VR', 'Unity', '...', 'Oculus'],
    longSkills: ['VR', 'Unity', 'C#', '3D', 'UI/UX', 'Oculus'],
  },
  'Hotdog Chase': {
    title: 'Hotdog Chase',
    description: 'VR game experience to collect hotdogs',
    subDescription: 'Virtual Reality on Google Cardboard',
    shortSkills: ['VR', 'Unity', '...', 'Google Cardboard'],
    longSkills: ['VR', 'Unity', 'C#', '3D', 'UI/UX', 'Google Cardboard'],
  },
  'Shift Payments': {
    title: 'Shift Payments',
    description: 'A motion graphics video intro on Shift Payments',
    shortSkills: ['Illustration', 'After Effects', 'Motion Graphics'],
    longSkills: ['Illustration', 'After Effects', 'Motion Graphics'],
  },
};
