export const PROJECT_DETAIL = {
  'Slope Ninja': {
    title: 'Slope Ninja',
    description: 'Snow updates for Tahoe Resorts',
    subDescription: 'Web and Mobile',
    shortSkills: ['React', 'React Native', 'Redux', 'node.js', '...', 'UI/UX'],
    longSkills: ['React', 'React Native', 'Redux', 'node.js', 'PostgreSQL', 'Koa', 'Knex', 'DynamoDB', 'Bootstrap Grid', 'UI/UX'],
  },
  Astroworker: {
    title: 'Astroworker',
    description: 'Get on-demand work',
    subDescription: 'Web',
    shortSkills: ['React', 'Redux', 'node.js', '...', 'UI/UX'],
    longSkills: ['React', 'Redux', 'node.js', 'PostgreSQL', 'Koa', 'Knex', 'UI/UX'],
    link: 'http://astroworker.com',
    text: 'astroworker.com',
  },
  Debut: {
    title: 'Debut',
    description: 'Beautiful, simple, clutter-free newsletters',
    subDescription: 'Web and Mobile',
    shortSkills: ['React', 'React Native', 'Redux', '...', 'UI/UX'],
    longSkills: ['React', 'React Native', 'Redux', 'Bootstrap Grid', 'UI/UX'],
  },
  Bagpal: {
    title: 'Bagpal',
    description: 'Social Platform for exchanging handbags',
    subDescription: 'Mobile',
    shortSkills: ['UI/UX'],
    longSkills: ['UI/UX'],
  },
  'Once Upon a Cloud': {
    title: 'Once Upon a Cloud',
    description: 'VR experience to learn about the earth water cycle',
    subDescription: 'Virtual Reality on Oculus',
    shortSkills: ['VR', 'Unity', '...', 'Oculus'],
    longSkills: ['VR', 'Unity', 'C#', '3D', 'UI/UX', 'Oculus'],
  },
  'Hotdog Chase': {
    title: 'Hotdog Chase',
    description: 'VR game experience to collect hotdogs',
    subDescription: 'Virtual Reality on Google Cardboard',
    shortSkills: ['VR', 'Unity', '...', 'Google Cardboard'],
    longSkills: ['VR', 'Unity', 'C#', '3D', 'UI/UX', 'Google Cardboard'],
  },
  'Shift Payments': {
    title: 'Shift Payments',
    description: 'A motion graphics video intro on Shift Payments',
    shortSkills: ['Illustration', 'After Effects', 'Motion Graphics'],
    longSkills: ['Illustration', 'After Effects', 'Motion Graphics'],
  },
};
