name: julia.dev CI

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Check out the changes
      - uses: actions/checkout@v2
      # Install node
      - uses: actions/setup-node@v1
        with:
          node-version: '14.2.0'
      # Utilize yarn cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # Install deps
      - run: yarn install --frozen-lockfile
      # Run tests
      - run: yarn test
